### ISSUE TITLE
Add in the template well-known prefixes

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#20]
It would be useful to include in the diagrams.net template main namespaces as owl, rdf, rds, dc, etc.

**Comment by Serge3006** [comment]
Those prefixes and namespaces are being handled internally, not needed to be specified explicitly.

**Comment by mariapoveda** [comment]
It is to facilitate it to the users. Or we can have one bulding block with the prefixes and another empty one.
