### ISSUE TITLE
Separate tables for different constructs

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#21]
For example in 2.2.3 Equivalent and Disjoint Classes create 1 table for equivalnet an another for  disjoint so that one does not read inmediately after the other, that is having some visual distinction.

 Same for 2.2.4 Intersection, Union and Complement of Classes. 

Another optin could be to separate each construct in one section, then splitting "2.2.3 Equivalent and Disjoint Classes " into 2 and 2.2.4 into 3.

**Comment by Serge3006** [comment]
Done!
