### ISSUE TITLE
Datatype properties in one class. Domain and Range

### ISSUE THREAD

**Issue by ednaru** [oeg-upm/chowlk_spec#26]
There may be data properties in one class where there are different conditions on domain and range. For example in Class C there are data properties A1 and A2, A1 has domain and range, A2 has has Domain and no range. Seems that graphical notation does not contemplate this case.

**Comment by mariapoveda** [comment]
It is considered as you can put 1 or many boxes below the class box. For example, one with the solid line for the attributes with domain and one  with dashed line for those datatype properties without domain. Then for each attribute you can say whehter they have range or not.

Thanks for the comment, we can make it explicit in the documentation.

**Comment by Serge3006** [comment]
I close this issue because this case is already covered in the notation, however, we will include more examples to explicitly indicate that case in the documentation.
