### ISSUE TITLE
Converting an existing OWL file into a Chowlk diagram

### ISSUE THREAD

**Issue by yoavnash** [oeg-upm/chowlk_spec#29]
Is it possible to convert an existing OWL file into a Chowlk diagram?
This could be useful if the OWL file was generated independently (e.g., via [Protégé](https://protege.stanford.edu/)), and you would like to use it as a basis for specific applications.

**Comment by Serge3006** [comment]
HI, this is something we will work on in the future as we have the problem of arranging the blocks properly, so they do not overlap.

**Comment by mariapoveda** [comment]
Closing this issue as we are moving to another repository.
