### ISSUE TITLE
Future inclusion of owl:oneOf

### ISSUE THREAD

**Issue by Serge3006** [oeg-upm/chowlk_spec#30]
The notation does not include the oneOf construct, it needs to be studied what is the best way to implement it visually.

**Comment by mariapoveda** [comment]
This only applies to the datatype case, for the use of owl:oneOf as group of individuals the shape used is the hexagon.

**Comment by Serge3006** [comment]
Yes, the owl:oneOf is represented by the following shape:

![image](https://user-images.githubusercontent.com/30761241/130249449-9362a9e4-1482-4e27-a7ef-2c483fb924d8.png)

**Comment by mariapoveda** [comment]
Done.
