### ISSUE TITLE
remove first draft in the website

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#31]
Remove "First Draft 04/06/202" and inlcude "Latest update"? Maybe in the footer?

then move all the following within the banner under the logo:

Chowlk Visual Notation

Authors:
María Poveda-Villalón (Ontology Engineering Group, Universidad Politécnica de Madrid)
Serge Chávez-Feria (Ontology Engineering Group, Universidad Politécnica de Madrid)

License:
Apache 2.0 License

Cite as:
Chowlk Visual Notation, Version 0.0.1.

**Comment by Serge3006** [comment]
I close this issue because the website will suffer a whole modification, so these changes will be reflected in the new version.
