### ISSUE TITLE
Add hexagon to main blocks

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#33]
add the hexagon shape to the list of main blocks. This is used for enumerations (oneOf).

**Comment by Serge3006** [comment]
The hexagon is being included in the new version of the website, which is not released yet. Here a snapshot of the proposed block:

![image](https://user-images.githubusercontent.com/30761241/129895128-ff7efd6a-c1c2-4854-ac89-143fdcf71142.png)
