### ISSUE TITLE
Propose a way to state more than one rdf:type

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#37]
when an individual belongs to more than one class, should it be possible to represent with the pile of boxes?

**Comment by Serge3006** [comment]
That feature is currently not supported. It would be difficult to differentiate attributes from classes in that particular case. To indicate that an individual pertains to more than one class it should be done with the arrows version.

![image](https://user-images.githubusercontent.com/30761241/129885588-2ed73f48-f146-4dd5-abf3-31a747a48cab.png)
