### ISSUE TITLE
wrong property in library for datavalues

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#38]
In the library the arrow is typed as objectProperty, I think it is better to be just ppropperty as it could be annotation or datatype too.

**Comment by Serge3006** [comment]
Not sure about this, this can cause confusion in the user. In the library and documentation, we have other blocks when we have to instantiate datatype properties.

![image](https://user-images.githubusercontent.com/30761241/129894833-6e26aacf-3ee2-4ed3-957a-4a667da1b9ea.png)
