### ISSUE TITLE
More compact rdf:type notation

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/chowlk_spec#41]
It would be good having a more compact notation for rdf.type when using an arrow as in the example: http://iot.linkeddata.es/def/core/index-en.html#ex1 

@Serge3006 Is it possible to implement it in the converter?

**Comment by Serge3006** [comment]
Yes, it is possible, if you go to the individuals section https://chowlk.linkeddata.es/chowlk_spec#individuals you will see that right now the class membership is represented by this arrow:
![image](https://user-images.githubusercontent.com/30761241/128740773-f06f05aa-0302-4cc3-bab1-27530b0dcdae.png)
The change will be to remove the rdf:type label from the arrow. It is fairly easy to detect this on the converter.

**Comment by mariapoveda** [comment]
OK but it should be in addition to the current notations, adding a new option.

**Comment by Serge3006** [comment]
It will be included in the new version of the website.
